name: boilerplate
version: 0.5.0
description: Example that shows how to upload files using Jaguar server
dependencies:
  jaguar: '>=0.5.3 <0.6.0'
  jaguar_reflect: '>=0.5.1 <0.6.0'
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
  http:
  jaguar_dev_proxy: ^0.0.4
  teja_http_json: ^0.0.1
  static_dom: ^0.0.1
  jaguar_static_file: ^0.5.1