name: boilerplate
version: 0.4.0
description: Example that shows how to upload files using Jaguar server
dependencies:
  jaguar: '>=0.4.0 <0.5.0'
  jaguar_reflect: '>=0.4.1 <0.5.0'
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
  http: '>=0.11.3+9 <0.12.0'
