name: boilerplate
version: 0.5.0
description: Example that shows how to upload files using Jaguar server
dependencies:
  jaguar: ^1.2.8
  http:
  jaguar_dev_proxy: ^1.2.0
  jaguar_client: ^0.2.0
  stencil: ^0.0.2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc